# Memoria máxima del proceso Gradle y codificación usada por el proyecto.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Mejora el rendimiento reutilizando resultados y ejecutando tareas en paralelo.
org.gradle.caching=true
org.gradle.parallel=true

# Indica que el proyecto utiliza las bibliotecas AndroidX.
android.useAndroidX=true

# Aplica el estilo oficial de Kotlin.
kotlin.code.style=official
